### ISSUE TITLE
Worldstate Trigger for creation of corresponding node Objects

### ISSUE THREAD

**Issue by dameiers** [crismaproject/cids-custom-crisma-server#2]
the currently used filesytem core does not support dynamic children. Therefore a trigger that rebuilds the structure of worldstates also for node objects is needed to workaround this limitiation

**Comment by mscholl** [comment]
@dameiers is this merged?

**Comment by dameiers** [comment]
closed via d61e902e376657a0b8ac068366194d8d15de4587
